### ISSUE TITLE
Digital Voting: Absentee Ballot

### ISSUE THREAD

**Issue by brenapp** [BenJetson/mannrobo.github.io-OLD#1]
Don't know where else to leave this, but will club members who will not be present on Voting Day (this Thursday) be given an absentee ballot? Since it's a digital election, I know this will probably not be that difficult, else I could get a proxy to enter my vote as instructed. Do you have any built in solutions?

**Comment by BenJetson** [comment]
The voting server runs locally only as of right now. I may cook up an absentee solution using GCSID authentication and Google Forms, but you'd have to enter your votes within a timeframe of about ten minutes and your GCSID username would be associated with your vote (visible to everyone). 

If you didn't get to submit anything somehow on Thursday, we'd make sure that your vote was counted somehow. I won't hit the "count ballots" button until everyone has submitted. :smile:

**Comment by ghost** [comment]
Absentee voting starts today at 4PM. Updates are sent out via Remind101. Be sure to click the links within 10 minutes.

**Comment by BenJetson** [comment]
Voting has closed as of today at 16:00. Results are available at https://www.goo.gl/7ZhqfX.
